# Generated by Django 6.0.4 on 2026-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_hiring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
