# Generated by Django 6.0.4 on 2026-04-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_company_alumni_is_hiring_alumni_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='pin',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
