# Generated by Django 6.0.4 on 2026-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alumni',
            name='hiring_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
