# Generated by Django 6.0.4 on 2026-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_remove_alumni_created_at_alumni_hiring_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='can_help_with',
            field=models.CharField(default='Career Guidance', max_length=200),
        ),
        migrations.AddField(
            model_name='alumni',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
