# Generated by Django 6.0.4 on 2026-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_can_help_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='can_help_with',
            field=models.CharField(default='Career Guidance', max_length=200),
        ),
    ]
